version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    environment:
      - PORT=${PORT:-8080}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ./:/app/
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - default
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - default

networks:
  default:
