version: '3'
services:
  redis:
    image: redis:alpine
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
      - /app/node_modules
    depends_on:
      - redis

