version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - usr/app/node_modules
    depends_on:
      - redis
  redis:
    image: redis:alpine

