version: '3'
services:
  redis:
    image: 'redis'
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    environment:
      - PORT=${PORT:-8080}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ./:/app/
      - /app/node_modules
    depends_on:
      - redis

